name: Run Container Scan on Super Mario Docker Image with Quality Gate

on:
  push:
    branches:
      - main

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Version Number
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get Docker Image from Docker Hub
        run: |
          echo "Pulling docker.io/obillor1/supermariorepo:${{ env.VERSION }}"
          docker pull docker.io/obillor1/supermariorepo:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/obillor1/supermariorepo:${{ env.VERSION }}
          ls -lh supermariolatestdockerimage.tar

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: ./supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
